name: pickup_lines
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.2
  shared_preferences: ^2.2.3
  clipboard: ^0.1.3
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/logo.jpg  # Path to your logo image

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true  # Remove alpha channel for iOS
  image_path: "lib/logo.jpg"  # Path to your logo image
