final Map<String, List<String>> pickupLinesByCategory = {
  'funny': [
    "Are you a magician? Because whenever I look at you, everyone else disappears.",
    "I must be a snowflake, because I've fallen for you.",
    "Do you believe in love at first sight, or should I walk by again?",
    "If you were a triangle, you'd be acute one.",
    "Do you have a map? Because I just got lost in your eyes.",
    "I’m no photographer, but I can definitely picture us together.",
    "Are you from Tennessee? Because you're the only ten I see!",
    "Is your dad a boxer? Because you're a knockout!",
    "I must be a keyboard, because you're just my type.",
    "Can I follow you home? Because my parents always told me to follow my dreams.",
    "Are you an alien? Because you just abducted my heart.",
    "Is your name Chapstick? Because you’re da balm!",
    "Are you a cat? Because I'm feline a connection.",
    "If you were a vegetable, you’d be a cute-cumber!",
    "Is your name Dunkin? Because I donut want to spend another day without you.",
    "Do you have a Band-Aid? Because I just scraped my knee falling for you.",
    "Is your dad a thief? Because he stole the stars and put them in your eyes.",
    "If you were a fruit, you’d be a fine-apple.",
    "I’d say God bless you, but it looks like he already did.",
    "Are you a beaver? Because daaaaam.",
    "Are you a time traveler? Because I see you in my future.",
    "Can I take you out for dinner? Because I can’t seem to get you out of my mind.",
    "You must be tired because you've been running through my mind all day.",
    "If you were a burger at McDonald's, you'd be the McGorgeous.",
    "Are you my phone charger? Because without you, I’d die.",
    "If looks could kill, you’d be a weapon of mass destruction.",
    "Do you have a name, or can I call you mine?",
    "You must be a magician because every time I look at you, everyone else disappears.",
    "Are you a loan from a bank? Because you have my interest!",
    "Do you like raisins? How do you feel about a date?",
    "You must be a campfire because you’re hot and I want s’more.",
    "Is your name Wi-Fi? Because I’m feeling a connection.",
    "You must be made of copper and tellurium because you’re Cu-Te.",
    "Is your name Google? Because you have everything I’m searching for.",
    "Are you a parking ticket? Because you’ve got ‘FINE’ written all over you.",
    "I’m not a hoarder, but I really want to keep you forever.",
    "If you were words on a page, you’d be fine print.",
    "Is your dad a baker? Because you’re a cutie pie.",
    "Did it hurt when you fell from heaven?",
    "You’re like a dictionary—you add meaning to my life.",
    "If you were a Transformer, you’d be Optimus Fine.",
    "You must be a magician because every time I look at you, everyone else disappears.",
    "Are you an angel? Because heaven is missing one.",
    "Are you a snowstorm? Because you make my heart race!",
    "Do you have a pencil? Because I want to erase your past and write our future.",
    "If you were a spice, you’d be paprika—because you add flavor to my life.",
    "Is your name Dunkin? Because I donut want to spend another day without you.",
    "You must be a magician because whenever I look at you, everyone else disappears.",
    "If we were at home, cuddling on a rainy Sunday morning, what would we have for breakfast? Maybe pancakes?",
    "You must be a magician because I’m under your spell.",
    "Are you a bank loan? Because you’ve got my interest!",
    "You must be a camera because every time I look at you, I smile.",
    "If you were a chicken, you’d be impeccable.",
    "Are you my homework? Because I’m not doing you, but I definitely should be.",
    "If you were a song, you'd be the best track on the album.",
    "Do you believe in love at first sight, or should I walk by again?",
    "Are you a time machine? Because I see you in my future.",
    "If you were a fruit, you’d be a peach.",
    "You must be tired because you've been running through my mind all day.",
    "Is your dad a gardener? Because you’re a blooming beauty.",
    "Are you a light bulb? Because you brighten up my day.",
    "If I could rearrange the alphabet, I’d put U and I together.",
    "You must be a parking ticket because you’ve got ‘FINE’ written all over you.",
    "If I were to ask you out, would your answer be the same as the answer to this question?",
    "Are you an artist? Because you just painted a smile on my face.",
    "You must be made of copper and tellurium because you're Cu-Te.",
  ],
  'romantic': [
    "Is your name Wi-Fi? Because I'm really feeling a connection.",
    "You must be tired because you've been running through my mind all day.",
    "If you were a fruit, you'd be a fine-apple!",
    "Are you a campfire? Because you’re hot and I want s'more.",
    "Your hand looks heavy—can I hold it for you?",
    "If beauty were a crime, you’d be serving a life sentence.",
    "You must be a star, because your beauty lights up the night.",
    "If kisses were snowflakes, I'd send you a blizzard.",
    "You must be made of copper and tellurium, because you're Cu-Te!",
    "I could travel the world, but I’d rather stay right here with you.",
    "You’re like a dream come true.",
    "You must be the square root of -1, because you can’t be real.",
    "If I could rearrange the alphabet, I’d put U and I together.",
    "Are you a sunset? Because you’re so beautiful.",
    "You must be the reason for global warming because you’re hot!",
    "I’d never play hide and seek with you because someone like you is impossible to find.",
    "You must be made of beryllium, gold, and titanium because you’re Be-Au-Ti-ful.",
    "If I were to ask you out, would your answer be the same as the answer to this question?",
    "You’re like a fine wine; the more of you I drink in, the better it gets.",
    "You’re so beautiful, you made me forget my pickup line.",
    "Are you a magician? Because whenever I look at you, everyone else disappears.",
    "Do you have a Band-Aid? Because I just scraped my knee falling for you.",
    "You must be a time traveler because I can see you in my future.",
    "If you were a vegetable, you’d be a cute-cumber.",
    "Your smile must be a black hole; nothing can escape its pull.",
    "Can I follow you? Because my parents always told me to follow my dreams.",
    "If I were to die tomorrow, I’d spend my last moments telling you how much I love you.",
    "You must be a campfire, because you're hot and I want s'more.",
    "You’re like a beautiful song that I never want to end.",
    "Is your heart a prison? Because I want to be sentenced for life.",
    "If beauty were a time, you’d be eternity.",
    "You’re the missing piece I’ve been trying to find.",
    "Are you from Tennessee? Because you're the only ten I see!",
    "Is your name Chapstick? Because you’re da balm!",
    "Are you a beaver? Because daaaaam.",
    "If you were a fruit, you’d be a fine-apple!",
    "I must be lost because heaven is a long way from here.",
    "You’re like a spark; you light up my world.",
    "Is your name Dunkin? Because I donut want to spend another day without you.",
    "Do you have a pencil? Because I want to erase your past and write our future.",
    "Your beauty must be a crime, because it’s punishable by life!",
    "Are you a time traveler? Because I see you in my dreams.",
    "If you were a star, you'd be the brightest in the sky.",
    "You must be the reason my heart races.",
    "Are you a flower? Because you make my heart bloom.",
    "Can you lend me a kiss? I promise I’ll give it back.",
    "You’re the peanut butter to my jelly.",
    "Is your name Google? Because you have everything I’m searching for.",
    "You’re like a candle in the wind, beautiful and rare.",
    "I didn’t believe in love at first sight until I saw you.",
    "If I were a cat, I'd spend all nine lives with you.",
    "You must be a magician because whenever I look at you, everyone else disappears.",
    "You make my heart skip a beat.",
    "You’re like my favorite song; I could listen to you forever.",
    "If we were both in a black hole, I would still find you.",
    "You must be a work of art because you’re breathtaking.",
    "Are you a wish? Because I just found you.",
    "You’re the melody that makes my heart sing.",
    "If I were to choose between breathing and loving you, I would use my last breath to say I love you.",
    "Your smile is like the sunrise; it brightens my day.",
    "Are you an angel? Because you just fell from heaven.",
    "You must be a time traveler because you’re always on my mind.",
    "If I were to write a book, you'd be the main character.",
    "Are you the ocean? Because I'm lost in your waves.",
  ],
  'nerdy': [
    "Are you made of copper and tellurium? Because you're Cu-Te.",
    "Do you like Star Wars? Because Yoda one for me!",
    "You're like a 90-degree angle—hot and perfectly straight.",
    "Are you a carbon sample? Because I want to date you.",
    "Are you an alien? Because you just abducted my heart.",
    "If you were a website, you’d be .com because you’re a total catch.",
    "You must be a high test score because I want to take you home and show you to my mother.",
    "Is your name Google? Because you have everything I’m searching for.",
    "Are you a black hole? Because you’re irresistible.",
    "You’re like a software update; whenever I see you, I think, ‘Not now.’",
    "Are you made of beryllium, gold, and titanium? Because you’re Be-Au-Ti.",
    "You must be a magician because every time I look at you, everyone else disappears.",
    "Are you a Wi-Fi signal? Because I'm feeling a connection.",
    "Are you a computer keyboard? Because you're just my type.",
    "You must be a high test score, because I want to take you home to meet my parents.",
    "Is your name Siri? Because you autocomplete me.",
    "You're like an algorithm; you're constantly running through my mind.",
    "Are you a piece of software? Because I can’t function without you.",
    "If we were both in a black hole, I would still find you.",
    "You must be a magician because every time I look at you, everyone else disappears.",
    "Are you a physics problem? Because you’ve got my heart racing.",
    "Are you a carbon-based life form? Because you’re simply amazing.",
    "If you were a superhero, you’d be the love of my life.",
    "Are you a game? Because I can’t stop playing with my feelings for you.",
    "Are you an astronaut? Because I’m lost in your eyes.",
    "Is your name Wi-Fi? Because I’m really feeling a connection.",
    "Do you believe in love at first sight, or should I walk by again?",
    "Is your name Tesla? Because you’ve got me charged up.",
    "Are you made of uranium? Because you’re U-235.",
    "Are you the square root of -1? Because you can't be real.",
    "You must be a quantum physicist because you’re messing with my mind.",
    "Are you a JavaScript function? Because you’re calling me!",
    "If you were a fruit, you’d be a fine-apple.",
    "Are you a periodic table? Because you’re an element of my heart.",
    "Is your name Dropbox? Because I want to store my heart in you.",
    "You’re like a puzzle; I can't seem to figure you out.",
    "Are you a coding error? Because I can't function without fixing you.",
    "Are you an equation? Because you’ve got my heart racing.",
    "If I were an enzyme, I’d be DNA helicase so I could unzip your genes.",
    "You must be the solution to my equation because you make everything better.",
    "Are you a circuit? Because you make my heart race.",
    "You’re like a rare collectible; I want to keep you forever.",
    "Are you a telescope? Because you’re making me see stars.",
    "If you were an app, you'd be the one I can't live without.",
    "Are you a magnet? Because you’re attracting me.",
    "If you were an operating system, you’d be my favorite version.",
    "Are you a data packet? Because I feel a connection.",
    "Do you believe in parallel universes? Because in every single one, I love you.",
    "Are you a science experiment? Because you’re making my heart react.",
    "Are you a computer? Because you’ve got all my tabs open.",
    "If you were an element, you'd be Francium, because you're extremely rare.",
    "Are you a smartphone? Because I can't help but check you out.",
    "You must be a programmer because you just compiled my heart.",
    "Are you a physics class? Because you’ve got my heart accelerating.",
    "You must be a Wi-Fi network because I’m feeling a strong connection.",
  ],
  'flirty': [
    "Excuse me, but I think you dropped something: my jaw!",
    "Do you have a Band-Aid? Because I just scraped my knee falling for you.",
    "Is your name Google? Because you have everything I’m searching for.",
    "Can you help me settle a bet? My friends say angels don’t exist, but I’m looking at one right now.",
    "I was blinded by your beauty... I’m going to need your name and number for insurance purposes.",
    "Do you believe in fate? Because I think we were meant to meet.",
    "You must be a magician, because every time I look at you, everyone else disappears.",
    "Do you have a pencil? Cause I want to erase your past and write our future.",
    "I must be lost because heaven is a long way from here.",
    "Are you a loan from a bank? Because you have my interest!",
    "Do you have a sunburn, or are you always this hot?",
    "Are you a campfire? Because you’re hot and I want s'more.",
    "If beauty were a crime, you’d be serving a life sentence.",
    "You must be a star because your beauty lights up the night.",
    "Are you a time traveler? Because I see you in my future.",
    "Is your dad a boxer? Because you’re a knockout!",
    "If kisses were snowflakes, I’d send you a blizzard.",
    "You must be a magician, because every time I look at you, everyone else disappears.",
    "If I could rearrange the alphabet, I’d put U and I together.",
    "You’re like a fine wine; the more of you I drink in, the better it gets.",
    "You’re so beautiful, you made me forget my pickup line.",
    "Do you have a map? Because I just got lost in your eyes.",
    "Are you French? Because Eiffel for you.",
    "If you were a vegetable, you’d be a cute-cumber!",
    "Your smile must be a black hole; nothing can escape its pull.",
    "If I were to ask you out, would your answer be the same as the answer to this question?",
    "Are you a parking ticket? Because you’ve got ‘FINE’ written all over you.",
    "You must be tired because you’ve been running through my mind all day.",
    "If I could rearrange the alphabet, I’d put U and I together.",
    "You’re like a dictionary—you add meaning to my life.",
    "Is your name Dunkin? Because I donut want to spend another day without you.",
    "Are you made of beryllium, gold, and titanium? Because you’re Be-Au-Ti.",
    "Can I take you out for dinner? Because I can’t seem to get you out of my mind.",
    "Is your heart a prison? Because I want to be sentenced for life.",
    "Are you a campfire? Because you’re hot and I want s'more.",
    "Did it hurt when you fell from heaven?",
    "Are you a magician? Because whenever I look at you, everyone else disappears.",
    "Do you believe in love at first sight, or should I walk by again?",
    "Are you a time traveler? Because I can see you in my future.",
    "If I could rearrange the alphabet, I’d put U and I together.",
    "You’re like a warm hug on a cold day.",
    "Are you a cupcake? Because you're sweet and irresistible.",
    "You must be made of stars because your beauty is out of this world.",
    "Do you have a mirror in your pocket? Because I can see myself in your pants.",
    "If you were a song, you’d be the best track on the album.",
    "Are you a magician? Because you just made my heart disappear.",
    "If you were a superhero, you’d be my favorite sidekick.",
    "Is your name Chapstick? Because you’re da balm!",
    "Are you a light bulb? Because you brighten my day.",
    "Can I follow you home? Because my parents always told me to follow my dreams.",
    "Do you have an extra heart? Because mine was just stolen.",
    "If you were a dessert, you’d be a sweet surprise.",
    "You must be a magician because every time I look at you, everyone else disappears.",
    "Are you a campfire? Because you’re hot and I want s'more.",
  ],
  'cheesy': [
    "Are you a parking ticket? Because you've got 'FINE' written all over you.",
    "If you were a vegetable, you'd be a cute-cumber!",
    "Is your dad a baker? Because you're a cutie pie!",
    "Do you like raisins? How do you feel about a date?",
    "If you were a burger at McDonald's, you'd be the McGorgeous.",
    "Do you have a sunburn, or are you always this hot?",
    "If you were a Transformer, you’d be Optimus Fine.",
    "Are you French? Because Eiffel for you.",
    "Are you an interior decorator? Because when I saw you, the entire room became beautiful.",
    "If beauty were a time, you'd be eternity.",
    "Is your name Chapstick? Because you’re da balm!",
    "If you were a fruit, you’d be a fine-apple.",
    "Are you a cat? Because I'm feline a connection between us.",
    "Is your dad a thief? Because he stole the stars and put them in your eyes.",
    "You must be a magician because every time I look at you, everyone else disappears.",
    "Did it hurt when you fell from heaven?",
    "If you were a vegetable, you'd be a cute-cumber.",
    "You’re like a fine wine; the more of you I drink in, the better it gets.",
    "You must be a time traveler because I can see you in my future.",
    "Are you a beaver? Because daaaaam.",
    "Are you a loan from a bank? Because you have my interest!",
    "You’re like a spark; you light up my world.",
    "If I could rearrange the alphabet, I’d put U and I together.",
    "You must be tired because you've been running through my mind all day.",
    "If beauty were a crime, you’d be serving a life sentence.",
    "Is your heart a prison? Because I want to be sentenced for life.",
    "You’re like a dictionary—you add meaning to my life.",
    "If I could rearrange the alphabet, I’d put U and I together.",
    "You must be the square root of -1, because you can’t be real.",
    "You’re the missing piece I’ve been trying to find.",
    "Is your name Dunkin? Because I donut want to spend another day without you.",
    "Are you a snowstorm? Because you make my heart race!",
    "Are you a magician? Because every time I look at you, everyone else disappears.",
    "If kisses were snowflakes, I'd send you a blizzard.",
    "You’re like a beautiful song that I never want to end.",
    "Are you a cupcake? Because you’re sweet and irresistible.",
    "You must be made of stars because your beauty is out of this world.",
    "Do you have a mirror in your pocket? Because I can see myself in your pants.",
    "If you were a dessert, you’d be a sweet surprise.",
    "You must be a magician because every time I look at you, everyone else disappears.",
    "Are you a campfire? Because you’re hot and I want s'more.",
    "Are you a piece of art? Because I want to hang you on my wall.",
    "Do you have an extra heart? Because mine was just stolen.",
    "You’re like a warm hug on a cold day.",
    "If I could follow you home, I would, but I can’t because my parents always told me to follow my dreams.",
    "Are you a camera? Because every time I look at you, I smile.",
    "Is your name Wi-Fi? Because I’m feeling a connection.",
    "You’re the peanut butter to my jelly.",
    "If you were a song, you’d be the best track on the album.",
    "Is your name Starbucks? Because I like you a latte.",
    "Are you an angel? Because heaven is missing one.",
    "You must be a parking ticket, because you've got 'FINE' written all over you.",
    "You’re like a light in the darkness.",
    "Are you a snowflake? Because I’ve fallen for you.",
    "Do you have a map? Because I just got lost in your eyes.",
  ],
  'savage': [
    "You're like a software update. Whenever I see you, I think, 'Not now.'",
    "I’d say God bless you, but it looks like he already did.",
    "You're not my type. But I’d definitely swipe right.",
    "Are you a time traveler? Because I see you in my future.",
    "I'd flirt with you, but I’d rather just compliment your outfit.",
    "You're like a dictionary—you add meaning to my life, but also make me confused.",
    "You're so full of yourself, even your reflection rolls its eyes.",
    "Are you made of beryllium, gold, and titanium? Because you're Be-Au-Ti.",
    "You're like a broken pencil—pointless.",
    "I'd agree with you, but then we'd both be wrong.",
    "You’re like a cloud. When you disappear, it’s a beautiful day.",
    "You look like trash—can I take you out?",
    "Are you a parking ticket? Because you've got 'FINE' written all over you.",
    "I’d call you a tool, but that implies you’re actually useful.",
    "If I had a dollar for every time I saw a beautiful woman, I’d have one dollar.",
    "You're like a candle in the wind—unpredictable.",
    "Are you my ex? Because I want to forget you.",
    "You're like a broken pencil—pointless.",
    "You bring everyone so much joy when you leave the room.",
    "I’d say you’re one in a million, but that means there are 7,000 people just like you.",
    "Do you have an eraser? Because I can’t get you out of my mind.",
    "You remind me of my next mistake.",
    "I’d explain it to you, but I left my English-to-Dingbat dictionary at home.",
    "If you were a vegetable, you’d be a cute-cumber!",
    "You must be a magician because every time I look at you, everyone else disappears.",
    "You look like you’d be fun to play with, but I’d rather not.",
    "Are you a keyboard? Because you’re just my type.",
    "You’re like a software update—nobody wants you around.",
    "I’d love to see things from your perspective, but I can’t get my head that far up my ass.",
    "If you were any more basic, you’d be a white girl.",
    "Do you believe in love at first sight, or should I walk by again?",
    "You’re like a light switch—you turn me on and off.",
    "You're like a software update; you make everything more complicated.",
    "You're the reason I have a headache.",
    "Are you a magician? Because every time I look at you, everyone else disappears.",
    "You look like the reason my parents had to get divorced.",
    "You’re like a participation trophy; everyone gets one but nobody wants you.",
    "I'd say you're as useless as the 'ueue' in 'queue'.",
    "If I wanted to hear from an asshole, I’d fart.",
    "You're like a cold pizza—good in theory, but still disappointing.",
    "I don't know what's longer, your last name or my patience.",
    "You’re like a broken clock; right twice a day but still annoying.",
    "Are you my phone charger? Because without you, I'm dead.",
    "You must be the reason the gene pool needs a lifeguard.",
  ],
  'cute': [
    "If you were a fruit, you’d be a fine-apple!",
    "Are you a cat? Because I'm feline a connection between us.",
    "You must be jelly, because jam don't shake like that!",
    "Do you like Star Wars? Because Yoda one for me!",
    "Are you a beaver? Because daaaaam.",
    "If I could rearrange the alphabet, I’d put U and I together.",
    "You must be a magician because every time I look at you, everyone else disappears.",
    "Are you a snowstorm? Because you make my heart race!",
    "You must be a campfire because you're hot and I want s'more.",
    "Do you believe in love at first sight, or should I walk by again?",
    "If you were a vegetable, you'd be a cute-cumber!",
    "Are you a banana? Because I find you a-peeling.",
    "You’re like a cupcake in a world of muffins.",
    "Is your name Wi-Fi? Because I’m feeling a connection.",
    "Are you a time traveler? Because I can see you in my future.",
    "Is your name Dunkin? Because I donut want to spend another day without you.",
    "Are you a magician? Because whenever I look at you, I smile.",
    "You’re the peanut butter to my jelly.",
    "You must be made of copper and tellurium, because you’re Cu-Te!",
    "Are you a campfire? Because you’re hot and I want s'more.",
    "Do you have a pencil? Cause I want to erase your past and write our future.",
    "Is your dad a baker? Because you're a cutie pie!",
    "You’re like a light in the darkness.",
    "If kisses were snowflakes, I’d send you a blizzard.",
    "You must be the reason for global warming because you’re hot!",
    "You’re like a song that I can’t get out of my head.",
    "Is your heart a prison? Because I want to be sentenced for life.",
    "You’re like a star; you light up my world.",
    "Are you a camera? Because every time I look at you, I smile.",
    "Is your name Starbucks? Because I like you a latte.",
    "You must be a parking ticket, because you've got 'FINE' written all over you.",
    "You’re like a warm hug on a cold day.",
    "Are you a snowflake? Because I’ve fallen for you.",
    "Do you have a map? Because I just got lost in your eyes.",
    "If you were a song, you’d be the best track on the album.",
    "Is your name Chapstick? Because you’re da balm!",
    "You’re like sunshine on a rainy day.",
    "Are you a rainbow? Because you make my heart colorful.",
    "If we were both socks, we’d make a great pair!",
    "You must be made of sugar, because you’re so sweet.",
    "If you were a cupcake, you’d be the one I’d want to eat.",
    "You’re like a flower; you brighten up my day.",
    "Are you a dictionary? Because you add meaning to my life.",
    "You’re like my favorite book; I can’t put you down.",
    "If I were to ask you out, would your answer be the same as the answer to this question?",
    "You must be a magician, because every time I look at you, everyone else disappears.",
    "You’re the sprinkles on my ice cream.",
    "Are you a light bulb? Because you brighten my day.",
    "You’re the cherry on top of my sundae.",
    "If I had a star for every time you brightened my day, I’d have a galaxy.",
    "Is your name Netflix? Because I could watch you all night.",
  ],
};
